config/routes.rb
Rails.application.routes.draw do
  root        'todos#index'

  resources   :todos do
    member do
      post 'add_favorite'
      post 'remove_favorite'
    end
  end

  get '/favorite_todos', to: 'todos#favorites'

  devise_for  :users
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :following_user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :favorite_todo,  class_name: 'Todo', foreign_key: 'todo_id'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :todo
  validates_presence_of :body
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user

  has_many :tasks
  accepts_nested_attributes_for :tasks, allow_destroy: true


  has_many :favorites
  has_many :following_users, through: :favorites

  validates_presence_of :title

  scope :public_to, lambda { |user|
    where("private = ? or user_id = ?", false, user.id)
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :todos
  has_many :favorites
  has_many :favorite_todos, through: :favorites

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!

  before_action :set_todo, only: [:show, :edit, :update, :destroy,
                                  :add_favorite, :remove_favorite]

  before_action :favorite_todos_list, only: [:index, :favorites]

  # GET /todos
  # GET /todos.json
  def index
    @todos = TodoPresenter.wrap(Todo.public_to current_user)
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
    @todo.tasks.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_url, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    @todo.user = current_user

    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todos_url, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.tasks.each(&:destroy)
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def favorites
    @todos = TodoPresenter.wrap(current_user.favorite_todos)
  end

  def add_favorite
    @todo.favorites.create(following_user: current_user)
    render json: @todo, status: 200
  end

  def remove_favorite
    @todo.following_users.delete(current_user)
    render json: @todo, status: 200
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    def favorite_todos_list
      @favorite_todo_ids = current_user.favorite_todos.all.map(&:id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params
        .require(:todo)
        .permit(:title, :private, :completed, tasks_attributes: [:body, :_destroy, :id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3">
      <%= yield %>
    </div>
  </div>

  <script>
    $(function(){
      Todo.init({
        signOutPath: "<%= destroy_user_session_path %>"
      });
    });
  </script>
</body>
</html>

app/views/todos/_form.html.erb
<%= simple_form_for(@todo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>

    <div class="form-group" id="task-fields-wrapper">
      <ul>
        <%= f.simple_fields_for(:tasks) do |task| %>
          <%= render "task_fields", f: task %>
        <% end %>
      </ul>

      <%= link_to_add_association 'add task', f, :tasks,
            'data-association-insertion-node' => "#task-fields-wrapper ul",
            'data-association-insertion-method' => "append" %>
    </div>

    <%= f.input :private %>
    <%= f.input :completed %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/todos/_header_list_todos.html.erb
<header class="header-todo-list clearfix">
  <h1>
    <%= header_title %>

    <%= link_to new_todo_path, class: "btn btn-primary pull-right add-todo-btn" do %>
      <i class="glyphicon glyphicon-plus" title="Add Todo"></i> <span class="hidden-xs">Add Todo</span>
    <% end %>
  </h1>
</header>

app/views/todos/_list_todos.html.erb
<table class="table table-hover todos-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th class="text-center">Favorite</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.title %></td>
        <td><%= todo.user.email %></td>
        <td class="text-center">
          <%= todo.favorite_star(@favorite_todo_ids) %>
        </td>
        <td>
          <%= link_to edit_todo_path(todo) do %>
            <i class="glyphicon glyphicon-edit"></i>
          <% end %>
        </td>
        <td>
          <%= link_to todo, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="glyphicon glyphicon-remove text-danger"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/todos/_nav_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Rails Todos</a>
  </div>
  <div id="navbar" class="navbar-collapse collapse in" aria-expanded="true" style="">
    <ul class="nav navbar-nav">
      <li><a href="<%= todos_path %>">Todos</a></li>
      <li><a href="<%= favorite_todos_path %>">Favorites</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="bg-danger">
        <a class="sign-out-btn" href="javascript:void(0);">Sign out</a>
      </li>
    </ul>
  </div>
</nav>

app/views/todos/_task_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls">
    <%= f.input :body, label: 'Task' %>

    <%= link_to_remove_association "remove", f %>
  </div>
</li>

app/views/todos/edit.html.erb
<%= render 'nav_header' %>

<h1>Editing Todo</h1>
<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/favorites.html.erb
<%= render 'nav_header' %>
<%= render 'header_list_todos', header_title: 'Favorite Todos' %>
<%= render 'list_todos' %>

app/views/todos/index.html.erb
<%= render 'nav_header' %>

<p class="bg-info" id="notice"><%= notice %></p>

<%= render 'header_list_todos', header_title: 'Todos' %>
<%= render 'list_todos' %>

app/views/todos/new.html.erb
<%= render 'nav_header' %>

<h1>New Todo</h1>
<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<%= render 'nav_header' %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Private:</strong>
  <%= @todo.private %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo.completed %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>